helper-operator:
      operators:
        camelk-operator:
          enabled: true
          syncwave: '0'
          namespace:
            name: camelktest
            create: true
          subscription:
            channel: 1.10.x
            approval: Manual
            operatorName: red-hat-camel-k
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            csv: red-hat-camel-k-operator.v1.10.6
            operatorgroup:
            create: true
            notownnamespace: true
helper-status-checker:
  enabled: true
